---
title: "Respiratory Rate Determination by Non-Invasive Means"
author: "Stephen Su, 844503, COMP90072"
output:
  pdf_document:
    keep_tex: true
    fig_caption: yes
    number_sections: yes
  css: style.css
bibliography: refs.bib
csl: apa.csl
urlcolor: blue
---

<style type="text/css">

body {
  font-family: serif;
  text-align: justify;
}

</style>

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  message = FALSE, warning = FALSE, echo = FALSE, dpi = 500,
  fig.height = 4, fig.align = "center", comment = "#>",
  dev.args = list(png = list(type = "cairo"))
)
```

```{r lib, include = FALSE}
library(tidyverse)
library(patchwork)
library(rlang)
library(zoo)
library(Rcpp)
sourceCpp("../src/model-df.cpp")
map(list.files("../R", full.names = TRUE), source)
```

```{r code, include = FALSE, cache = FALSE}
read_chunk("report.R")
```

# Introduction

## Background

[@apnea2000].

# The data

## Data source

[@physiobank2000].

## Sample plot

```{r data}
```

```{r rr-interval}
```

\newpage

## Respiratory analysis (Subject a02)

```{r resp}
```

\newpage

# References
